#!/usr/bin/env bash
# Phase 13: install PLDDS onto a real dual-boot machine, alongside an
# existing Windows install, without touching Windows itself.
#
# Order of operations enforced by this script (do not skip steps by
# calling pieces manually unless you know exactly what you're doing):
#   1. preflight-check.sh must have passed (this script re-checks the
#      critical bits, but doesn't replace running it yourself first).
#   2. backup-grub-config.sh — snapshot the CURRENT working GRUB config.
#   3. Copy vmlinuz + initramfs.cpio.gz onto the ESP under /pldds/.
#   4. Append (never overwrite) the diagnostic + diagnostic-safe
#      menuentries via /etc/grub.d/41_pldds (a NEW file — Windows'
#      entry and everything else already in grub.cfg is untouched).
#   5. Substitute the real ${PLDDS_BOOT_PARTITION_UUID} /
#      ${EFI_SYSTEM_PARTITION_UUID} placeholders from
#      diagnostic/grub/grub.cfg with this machine's actual UUIDs.
#   6. Run update-grub / grub-mkconfig to regenerate grub.cfg — this is
#      the ONLY step that touches the live grub.cfg, and it's the
#      distro's own tool doing it (not this script hand-editing GRUB's
#      generated output).
#   7. Verify: parse the regenerated grub.cfg and confirm "windows" is
#      still the default entry and both PLDDS entries are present.
#
# core safety invariant (see docs/architecture.md): this script NEVER
# writes to the Windows partition, NEVER changes GRUB's persistent
# default away from "windows", and NEVER calls grub-set-default. The
# only thing that can point at "diagnostic" is a one-shot grub-reboot,
# and only PLDDS's own init does that (not this installer).

set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must be run as root (sudo $0)" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIAG_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
VMLINUZ="${DIAG_DIR}/build/output/vmlinuz"
INITRD="${DIAG_DIR}/build/output/initramfs.cpio.gz"
GRUB_TEMPLATE="${DIAG_DIR}/grub/grub.cfg"

ESP="${PLDDS_ESP_PATH:-$(bootctl --print-esp-path 2>/dev/null || echo /boot/efi)}"

echo "PLDDS Phase 13 — install"
echo "========================="
echo "ESP:            ${ESP}"
echo "vmlinuz:         ${VMLINUZ}"
echo "initramfs:       ${INITRD}"
echo

# --- Step 1: re-verify the critical safety preconditions -------------------
[ -f "${VMLINUZ}" ] || { echo "ERROR: ${VMLINUZ} not found — build it first" >&2; exit 1; }
[ -f "${INITRD}" ]  || { echo "ERROR: ${INITRD} not found — build it first" >&2; exit 1; }
[ -f "${ESP}/EFI/Microsoft/Boot/bootmgfw.efi" ] || {
    echo "ERROR: ${ESP}/EFI/Microsoft/Boot/bootmgfw.efi not found." >&2
    echo "Refusing to proceed — this script only supports adding PLDDS alongside an existing Windows UEFI install, and can't find one." >&2
    exit 1
}

read -r -p "This will add GRUB menu entries and copy PLDDS boot files to ${ESP}. Windows itself will NOT be modified. Continue? [y/N] " CONFIRM
if [ "${CONFIRM}" != "y" ] && [ "${CONFIRM}" != "Y" ]; then
    echo "Aborted — nothing was changed."
    exit 0
fi

# --- Step 2: backup current GRUB state first --------------------------
echo "[install] backing up current GRUB config..."
"${SCRIPT_DIR}/backup-grub-config.sh"

# --- Step 3: copy boot files onto the ESP -----------------------------
echo "[install] copying boot files to ${ESP}/pldds/"
install -d -m 0755 "${ESP}/pldds"
install -m 0644 "${VMLINUZ}" "${ESP}/pldds/vmlinuz"
install -m 0644 "${INITRD}" "${ESP}/pldds/initramfs.cpio.gz"

# --- Step 4/5: determine real UUIDs, render the GRUB snippet --------------
PLDDS_PART_DEV="$(df --output=source "${ESP}" | tail -1)"
PLDDS_BOOT_PARTITION_UUID="$(blkid -s UUID -o value "${PLDDS_PART_DEV}")"

# The Windows/ESP partition and the partition PLDDS boots the kernel
# from are the SAME partition in this install layout (kernel + initramfs
# just live in a /pldds/ subdirectory of the existing ESP — no new
# partition needed, and no risk of GRUB "search" finding the wrong disk).
EFI_SYSTEM_PARTITION_UUID="${PLDDS_BOOT_PARTITION_UUID}"

if [ -z "${PLDDS_BOOT_PARTITION_UUID}" ]; then
    echo "ERROR: could not determine UUID of ${PLDDS_PART_DEV} (blkid failed)" >&2
    exit 1
fi

echo "[install] ESP device:    ${PLDDS_PART_DEV}"
echo "[install] ESP UUID:      ${PLDDS_BOOT_PARTITION_UUID}"

CUSTOM_SNIPPET=/etc/grub.d/41_pldds
echo "[install] writing ${CUSTOM_SNIPPET}"

{
    echo "#!/bin/sh"
    echo "# Auto-generated by diagnostic/install/install.sh — DO NOT EDIT BY HAND."
    echo "# To remove: diagnostic/install/uninstall.sh (or just delete this file"
    echo "# and re-run update-grub)."
    echo "exec cat << 'PLDDS_GRUB_EOF'"
    sed \
        -e "s/\${PLDDS_BOOT_PARTITION_UUID}/${PLDDS_BOOT_PARTITION_UUID}/g" \
        -e "s/\${EFI_SYSTEM_PARTITION_UUID}/${EFI_SYSTEM_PARTITION_UUID}/g" \
        "${GRUB_TEMPLATE}" \
        | grep -A 100 '^menuentry "PLDDS Diagnostic Linux"' \
        | sed -n '/^menuentry "PLDDS Diagnostic Linux"/,/^}/p; /^menuentry "PLDDS Diagnostic Linux (safe mode)"/,/^}/p'
    echo "PLDDS_GRUB_EOF"
} > "${CUSTOM_SNIPPET}"
chmod 0755 "${CUSTOM_SNIPPET}"

# Sanity-check the snippet actually captured both menuentries before
# handing off to update-grub — an empty/partial snippet would silently
# produce a GRUB menu with no working diagnostic entry.
if ! grep -q 'id diagnostic ' "${CUSTOM_SNIPPET}" || ! grep -q 'id diagnostic-safe' "${CUSTOM_SNIPPET}"; then
    echo "ERROR: ${CUSTOM_SNIPPET} does not contain both expected menuentries — aborting before touching grub.cfg." >&2
    echo "This usually means diagnostic/grub/grub.cfg's format changed without this installer being updated to match." >&2
    rm -f "${CUSTOM_SNIPPET}"
    exit 1
fi

# --- Step 6: regenerate grub.cfg via the distro's own tooling --------------
echo "[install] regenerating grub.cfg..."
if command -v update-grub >/dev/null 2>&1; then
    update-grub
elif command -v grub-mkconfig >/dev/null 2>&1; then
    GRUB_CFG_OUT="$(dirname "$(cat /var/lib/pldds/grub-backup/MANIFEST.txt 2>/dev/null | grep 'original grub.cfg path' | cut -d: -f2- | xargs)")"
    grub-mkconfig -o "${GRUB_CFG_OUT:-/boot/grub/grub.cfg}"
else
    echo "ERROR: neither update-grub nor grub-mkconfig found." >&2
    exit 1
fi

# --- Step 7: verify the result before declaring success --------------------
GRUB_CFG="$(grep 'original grub.cfg path' /var/lib/pldds/grub-backup/MANIFEST.txt | cut -d: -f2- | xargs)"
echo "[install] verifying ${GRUB_CFG}..."

FAIL=0
if ! grep -q 'set default="windows"' "${GRUB_CFG}"; then
    echo "ERROR: default entry is not \"windows\" after regeneration — this violates the core safety invariant. NOT leaving this in place." >&2
    FAIL=1
fi
if ! grep -q '--id diagnostic ' "${GRUB_CFG}" && ! grep -q "--id 'diagnostic'" "${GRUB_CFG}"; then
    echo "ERROR: 'diagnostic' menuentry not found in regenerated grub.cfg." >&2
    FAIL=1
fi
if ! grep -q 'Windows Boot Manager' "${GRUB_CFG}"; then
    echo "ERROR: Windows Boot Manager entry not found in regenerated grub.cfg — something is very wrong, restore immediately." >&2
    FAIL=1
fi

if [ "${FAIL}" -eq 1 ]; then
    echo
    echo "Verification FAILED. Restoring the pre-install grub.cfg now." >&2
    "${SCRIPT_DIR}/uninstall.sh" --restore-only
    exit 1
fi

echo
echo "[install] SUCCESS."
echo "  - Windows remains the default GRUB entry (verified)."
echo "  - New entries: 'PLDDS Diagnostic Linux', 'PLDDS Diagnostic Linux (safe mode)'."
echo "  - Backup of your original grub.cfg: /var/lib/pldds/grub-backup/"
echo "  - To fully remove PLDDS and restore original GRUB: diagnostic/install/uninstall.sh"
echo
echo "NEXT: reboot and confirm the GRUB menu shows all three entries, Windows"
echo "still boots by default/by hand, and only THEN test selecting the PLDDS"
echo "entry manually (do not rely on grub-reboot for the very first boot test)."
